wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1651093983
    t:
      1:
      - 1
      - 30
      - 41
      - 55
      2:
      - 1
      - 30
      - 41
      - 55
      3:
      - 16
      4: 3.8.10
      5: 0.12.14
      8:
      - 5
batch_size:
  desc: null
  value: 16
dataset:
  desc: null
  value: LunarLanderContinuous-v2
learning_rate:
  desc: null
  value: 0.01
model:
  desc: null
  value: Weighted multi actor weight
